# frozen_string_literal: true

require "erb"
require "rubocop"
require "shipshape/guards"
require "shipshape/install"
require "shipshape/settings"
require "shipshape/typed_arguments"

module Shipshape
  # Writes the rules file an agent is handed. Everything in it is derived from the configuration,
  # the cop registry and the installed templates, so nothing can fall behind the code it
  # describes. Regenerate it rather than editing it.
  class Rules
    include TypedArguments

    HEADER = "<!-- generated by shipshape; run `shipshape rules` to refresh -->"

    # Keyed to the method name, so a rename orphans the key rather than the description —
    # `VocabularyTest` reddens on a name in neither this map nor VOCABULARY_EXCLUSIONS.
    VOCABULARY_DESCRIPTIONS = {
      "call" => "the entry point every operation and workflow answers to.",
      "test_call" => "skips the permission check, for building state a test needs.",
      "call_later" => "defers the call to a job, answering `success(:enqueued)` immediately.",
      "success" => "builds the `Result` a writing operation answers with when it worked.",
      "failure" => "builds the `Result` a writing operation answers with when it did not — an " \
                   "error code and, optionally, a value to redraw a form with.",
      "success?" => "`Result`'s own predicate for which one came back.",
      "shapes?" => "the check a question's answer must pass: nil, a `Shape`, or an array of them.",
      "typed" => "asserts an argument's class at construction; raises rather than coercing.",
      "typed_array" => "the same assertion over every element of an Array.",
      "typed_hash" => "the same assertion over every key and value of a Hash.",
      "typed_enum" => "asserts a value is one of a closed Array of literals, by membership.",
      "permission" => "the operation's own grantable name — always its class name, never chosen.",
      "anonymous?" => "true for an operation that implements `anonymous_call` instead of `call`.",
      "to_h" => "a `Shape`'s round trip: instance variables out as a Hash, `new(**shape.to_h)` " \
                "back in — only when the keywords match the fields.",
      "==" => "a `Shape`'s own equality: two are equal when their fields are.",
      "integer_param" => "parses `params[key]` as an Integer.",
      "integer_param!" => "same, bouncing (`TypedParams::BadParam`) instead of falling back.",
      "decimal_param" => "parses `params[key]` as a `BigDecimal`.",
      "decimal_param!" => "same, bouncing instead of falling back.",
      "boolean_param" => "parses `params[key]` as `true`/`false` from `1`/`0`/`true`/`false`.",
      "boolean_param!" => "same, bouncing instead of falling back.",
      "text_param" => "a trimmed String from `params[key]`, bounded by `limit:`.",
      "text_param!" => "same, bouncing instead of falling back.",
      "enum_param" => "parses `params[key]`, refusing anything outside the given list.",
      "enum_param!" => "same, bouncing instead of falling back.",
      "time_zone_param" => "parses `params[key]` as an `ActiveSupport::TimeZone`.",
      "time_zone_param!" => "same, bouncing instead of falling back.",
      "date_param" => "parses `params[key]` as a `Date`, resolved against `time_zone:`.",
      "date_param!" => "same, bouncing instead of falling back.",
      "time_param" => "parses `params[key]` as a `Time`, refusing an offset that contradicts " \
                       "`time_zone:`.",
      "time_param!" => "same, bouncing instead of falling back.",
    }.freeze

    # Everything else the templates define, and why an application never writes it. Being
    # listed is what grants the exclusion; a renamed or newly public method has none yet.
    VOCABULARY_EXCLUSIONS = {
      "to_s" => "Ruby's own conversion protocol on the `Boolean` marker.",
      "inspect" => "Ruby's own inspection protocol; read by `p`, never called by name.",
      "refuse_record" => "the guard `typed` runs before it looks at the type at all.",
      "matches?" => "the type check behind `typed`.",
      "mismatch_message" => "the error text `typed` raises when the check fails.",
      "catalogue" => "reads every operation's permission at once for a capability screen — not " \
                      "written inside an operation.",
      "permissions" => "the aggregate a workflow or a capability screen reads; an operation's " \
                        "own body asks `permission`, singular.",
      "aggregate" => "the recursion behind `permissions`.",
      "reaches" => "the call-graph edge `permissions` walks.",
      "permits?" => "marked private in `Permission` itself; only `call` asks it.",
      "initialize" => "the base classes' own inner value and exception types build these " \
                       "through `.new` or `raise`; an application writes its own `initialize`.",
      "in" => "reads a method's syntax tree for what it calls, to build the permission graph.",
      "operation?" => "asks whether a found constant answers like an operation, from `Calls.in`.",
      "resolve" => "resolves a constant name found by `Calls.in`.",
      "nesting" => "the lexical scope `Calls.in` resolves a name against.",
      "read_nesting" => "reads that scope off the file on disk.",
      "enclosing_scopes" => "walks a syntax tree for `read_nesting`.",
      "constants_in" => "walks a syntax tree for the constants `Calls.in` found.",
      "runs_a_constant?" => "the node test behind `constants_in`.",
      "constant_name" => "renders a constant node back to a name.",
      "edges" => "reads the whole call graph for a rake task or admin screen, not from inside " \
                 "an operation.",
      "grantable" => "same family as `edges` — an audit of the graph, not a call an operation makes.",
      "routes" => "same family — walks the router for a permissions audit.",
      "unchecked" => "same family — lists anonymous operations for an audit.",
      "leaks" => "same family — finds a guarded operation an anonymous one reaches.",
      "endpoint" => "the private row `routes` builds per route.",
      "controller_for" => "resolves a route to its controller, for `endpoint`.",
      "camelize" => "the path-to-constant mangling `controller_for` needs.",
      "permissions_of" => "flattens a list of operations to their demands.",
      "rails_application" => "the default `routes` reads when none is given.",
      "operations" => "the private lookup `edges`/`grantable`/etc. share for a door's descendants.",
      "entry_point" => "picks `call` or `anonymous_call` for `edges` to read.",
      "record?" => "asks whether one value is a record, for `anywhere_in?`.",
      "anywhere_in?" => "the guard `typed` and `Shape`'s own `new` run before an argument is held.",
      "new" => "wires the record guard into `Shape`/`ApplicationViewComponent`'s constructor; " \
               "an application calls the constructor it already knows, not this.",
      "refuse_records" => "the private half of that guard.",
      "hash" => "Ruby's own object protocol (`Array#uniq`, `Hash` keys); overridden for value " \
                "semantics, not called by name.",
      "eql?" => "Ruby's own Hash-key contract, aliased to `==`; not a second equality to write.",
      "state" => "the protected fields `==` and `hash` compare.",
      "record" => "written automatically by every writing door's `call`; an application never " \
                  "calls it.",
      "entry" => "builds the row `record` writes.",
      "redact" => "strips personal fields before `entry` writes the row.",
      "personal?" => "asks whether one argument name is a declared personal column.",
      "sink" => "the internal getter `record` reads; an application points it once with " \
                "`AuditLog.sink=`, an attr_writer, not this.",
      "perform" => "the transaction/permission wrapper `call` opens, or the hook the job " \
                   "runner invokes to run a deferred deed — never called by name.",
      "actor_finder" => "the lookup `perform` uses to rebuild a deferred actor; configured " \
                         "once via `actor_finder=`, not called by name.",
      "attempts_for" => "the retry limit `perform` reads off the operation.",
      "backoff" => "the wait `perform` computes between retries.",
      "actor" => "`OperationJob`'s private lookup of the actor by class and id.",
      "refuse_unidentifiable" => "`call_later`'s own guard that the actor can be rebuilt in the job.",
      "queue_name" => "read via a `QUEUE` constant on the operation, never called by name.",
      "excluded_from_audit" => "read via an `EXCLUDE_FROM_AUDIT` constant, never called by name.",
      "aggregate_steps" => "the recursion behind a workflow's `permissions`.",
      "steps" => "reads `call`'s own source to find what it sequences; not called by name.",
      "included" => "Ruby's `Module#included` hook, run automatically when the concern is mixed in.",
      "bounce" => "the `rescue_from` handler `included` wires up; never called directly.",
      "refuse_conflicting_zone" => "the guard `time_param` runs before answering.",
      "named_zone" => "resolves the zone `date_param`/`time_param` parse against.",
      "parsed_param" => "the engine every `_param` method shares.",
      "route" => "reads the registry a column declares; an application checks " \
                 "`PersonalData::COLUMNS` directly.",
      "declared?" => "same family as `route`.",
      "tables_needing_erasure" => "same family — read by the generated compliance test.",
    }.freeze

    def initialize(config:, root: Dir.pwd)
      @config = config
      @root = typed(root, String)
    end

    def call
      [HEADER, preamble, vocabulary_section, kinds_section, matrix_section, guards_section,
       authorisation_section]
        .compact
        .join("\n\n")
        .concat("\n")
    end

    private

    attr_reader :config, :root

    def settings
      @settings ||= Settings.layout(config)
    end

    def preamble
      <<~TEXT.strip
        # How code is shaped here

        Every class is one **kind**, decided by what it inherits. A kind may only call the
        kinds listed for it below — that is the whole architecture, and #{cops.length} cops
        hold it. Run `shipshape check` before you push: it counts offences against the merge
        base, so a count may fall and never rise.
      TEXT
    end

    def kinds_section
      rows = settings.kinds.map do |kind, globs|
        "| `#{kind}` | #{globs.map { |g| "`#{g}`" }.join(', ')} | " \
          "#{settings.retiring?(kind) ? 'on its way out — never move code here' : 'yes'} |"
      end

      <<~TEXT.strip
        ## The kinds

        A kind marked on its way out is a waypoint, not a destination. Code leaves it; nothing
        new arrives. Refactoring into one is how a migration stops half way.

        | kind | where it lives | a destination? |
        |---|---|---|
        #{rows.join("\n")}
      TEXT
    end

    def matrix_section
      rows = settings.matrix.map do |kind, reachable|
        "| `#{kind}` | #{reachable.empty? ? '— nothing' : reachable.map { |r| "`#{r}`" }.join(', ')} |"
      end

      <<~TEXT.strip
        ## What may call what

        No kind calls its own kind, or a sister of it. Two deeds always done together are one
        deed — a deed that calls a deed is a workflow that never said so.

        | this kind | may call |
        |---|---|
        #{rows.join("\n")}
      TEXT
    end

    def guards_section
      rows = cops.map { |name| "- **`#{name}`** — #{description_of(name)}" }

      <<~TEXT.strip
        ## The guards

        Each fails with the rule, the reason, and an example to copy. Read the failure; it is
        written to be the whole context.

        #{rows.join("\n")}
      TEXT
    end

    def authorisation_section
      return unless installed_auth?

      <<~TEXT.strip
        ## Authorisation

        Every operation takes `actor:` and its permission **is** its class name. The base
        class checks it before the work, so no operation writes a permission check of its
        own. An operation that runs before anyone is identified implements `anonymous_call`
        instead of `call` — that is a property of the class, and there is no way for a caller
        to ask for it. A workflow's steps are read out of its `call`, and it is refused whole
        before the first one runs.
      TEXT
    end

    # Placed early: an agent stopping at the first screen should still meet these names.
    # Presence, not privacy — `typed` is private in Ruby's own sense and still belongs here.
    def vocabulary_section
      rows = VOCABULARY_DESCRIPTIONS.filter_map { |name, text| vocabulary_row(name, text) }

      <<~TEXT.strip
        ## The vocabulary

        The names an operation's own body writes, not the machinery under them.

        #{rows.join("\n")}
      TEXT
    end

    def vocabulary_row(name, text)
      return unless defined_anywhere?(name)

      kinds = kinds_defining(name)

      "- **`#{name}`** — #{text}#{kinds.empty? ? '' : " (#{kind_annotation(kinds)})"}"
    end

    def kind_annotation(kinds)
      kinds == operation_kinds ? "every operation kind" : kinds.sort.join(", ")
    end

    # A template's own file name is its kind's name — read from the configuration, not repeated.
    def kind_templates
      @kind_templates ||= Install::FILES & settings.kinds.keys
    end

    # `Shape` is a kind, but not an operation: it has no `call`, so it is not in this set.
    def operation_kinds
      @operation_kinds ||= kind_templates - ["shape"]
    end

    def kinds_defining(name)
      kind_templates.select { |kind| defined_in?(kind, name) }
    end

    def defined_anywhere?(name)
      installed_templates.any? { |file| defined_in?(file, name) }
    end

    # No `\b`: it never matches after `?`/`!`. The lookahead instead refuses a longer name this
    # one is only a prefix of — `call` must not match `call_later`.
    def defined_in?(file, name)
      rendered_template(file).match?(/^\s*def\s+(?:self\.)?#{Regexp.escape(name)}(?![a-zA-Z0-9_?!])/)
    end

    # `Install`'s own selection, not a second copy of its AUTH_ONLY/VIEW_COMPONENT_ONLY subtraction.
    def installed_templates
      Install.new(root: root, auth: installed_auth?, view_components: installed_view_components?).files
    end

    # The disk file this application actually has, read as-is; the template only for a kind
    # nothing has written yet — `install` never overwrites, so the two can disagree.
    def rendered_template(name)
      @rendered_templates ||= {}
      @rendered_templates[name] ||= installed_source(name) || render_current_template(name)
    end

    def installed_source(name)
      path = installed_path(name)
      File.read(path) if File.file?(path)
    end

    def installed_path(name)
      File.join(root, Install::DIRECTORY, "#{name}.rb")
    end

    def render_current_template(name)
      auth = installed_auth?
      path = File.join(Install::TEMPLATES, "#{name}.rb.tt")

      ERB.new(File.read(path), trim_mode: "-").result(binding)
    end

    # `permission`/`anonymous?` are mixed into `deed.rb` (`extend Permission`), never defined
    # in `permission.rb` itself, so a stale, never-overwritten `deed.rb` leaves them exactly
    # as unreachable as a missing `test_call` even once `permission.rb` exists on disk.
    def installed_auth?
      @installed_auth = (installed_source("deed") || "").include?("extend Permission") if
        @installed_auth.nil?
      @installed_auth
    end

    def installed_view_components?
      @installed_view_components = File.file?(installed_path("application_view_component")) if
        @installed_view_components.nil?
      @installed_view_components
    end

    # A cop that is not running holds nothing, so it is not one of the guards this file claims.
    # Its own disclosure is `shipshape check`'s job — see docs/decomposing/an-adoption-order.md.
    def cops
      @cops ||= RuboCop::Cop::Registry.global.cops
                                      .map(&:cop_name)
                                      .grep(%r{\AShipshape/})
                                      .reject { |name| disabled?(name) }
                                      .sort
    end

    # The same question `Guards` asks of a subprocess, asked here of the `RuboCop::Config`
    # already in hand: `Config#enabled_new_cop?` is RuboCop's own resolution of whether a
    # `pending` cop runs, department overrides and version-pinned `NewCops` included.
    def disabled?(name)
      Guards.disabled?(config.for_cop(name)["Enabled"], new_cop_enabled: config.enabled_new_cop?(name))
    end

    # Squeezed because YAML folds the Description and a rules file wants it on one line.
    def description_of(name)
      config.for_cop(name).fetch("Description", "").gsub(/\s+/, " ").strip
    end
  end
end
