# frozen_string_literal: true

require "rubocop"
require "shipshape/settings"
require "shipshape/typed_arguments"

module Shipshape
  # Writes the rules file an agent is handed. Everything in it is derived — kinds and matrix from
  # the configuration, cops from the registry, authorisation from the base class on disk — so
  # nothing can fall behind the code. Regenerate it rather than editing it.
  class Rules
    include TypedArguments

    HEADER = "<!-- generated by shipshape; run `shipshape rules` to refresh -->"

    def initialize(config:, root: Dir.pwd)
      @config = config
      @root = typed(root, String)
    end

    def call
      [HEADER, preamble, kinds_section, matrix_section, guards_section, authorisation_section]
        .compact
        .join("\n\n")
        .concat("\n")
    end

    private

    attr_reader :config, :root

    def settings
      @settings ||= Settings.layout(config)
    end

    def preamble
      <<~TEXT.strip
        # How code is shaped here

        Every class is one **kind**, decided by what it inherits. A kind may only call the
        kinds listed for it below — that is the whole architecture, and #{cops.length} cops
        hold it. Run `shipshape check` before you push: it counts offences against the merge
        base, so a count may fall and never rise.
      TEXT
    end

    def kinds_section
      rows = settings.kinds.map { |kind, globs| "| `#{kind}` | #{globs.map { |g| "`#{g}`" }.join(', ')} |" }

      <<~TEXT.strip
        ## The kinds

        | kind | where it lives |
        |---|---|
        #{rows.join("\n")}
      TEXT
    end

    def matrix_section
      rows = settings.matrix.map do |kind, reachable|
        "| `#{kind}` | #{reachable.empty? ? '— nothing' : reachable.map { |r| "`#{r}`" }.join(', ')} |"
      end

      <<~TEXT.strip
        ## What may call what

        No kind calls its own kind, or a sister of it. Sequencing two writes is a workflow's
        job, and a command that calls a command is a workflow that never said so.

        | this kind | may call |
        |---|---|
        #{rows.join("\n")}
      TEXT
    end

    def guards_section
      rows = cops.map { |name| "- **`#{name}`** — #{description_of(name)}" }

      <<~TEXT.strip
        ## The guards

        Each fails with the rule, the reason, and an example to copy. Read the failure; it is
        written to be the whole context.

        #{rows.join("\n")}
      TEXT
    end

    def authorisation_section
      return unless File.exist?(File.join(root, "app/shipshape/permission.rb"))

      <<~TEXT.strip
        ## Authorisation

        Every operation takes `actor:` and its permission **is** its class name. The base
        class checks it before the work, so no operation writes a permission check of its
        own. An operation that runs before anyone is identified implements `anonymous_call`
        instead of `call` — that is a property of the class, and there is no way for a caller
        to ask for it. A workflow's steps are read out of its `call`, and it is refused whole
        before the first one runs.
      TEXT
    end

    def cops
      @cops ||= RuboCop::Cop::Registry.global.cops
                                      .map(&:cop_name)
                                      .grep(%r{\AShipshape/})
                                      .sort
    end

    # Squeezed because YAML folds the Description and a rules file wants it on one line.
    def description_of(name)
      config.for_cop(name).fetch("Description", "").gsub(/\s+/, " ").strip
    end
  end
end
